src/Entity/News.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 */
class News
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=10)
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="news", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug() : ?string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setNews($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getNews() === $this) {
                $comment->setNews(null);
            }
        }

        return $this;
    }
}

src/Form/NewsType.php
<?php

namespace App\Form;

use App\Entity\News;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NewsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('image')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => News::class,
            'translation_domain' => 'forms'
        ]);
    }
}

src/Controller/NewsController.php
<?php

namespace App\Controller;

use App\Entity\News;
use App\Form\NewsType;
use App\Entity\Comment;
use App\Form\CommentType;

use App\Repository\NewsRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class NewsController extends AbstractController
{
    /**
     * @Route("/news", name="news")
     */
    public function index(NewsRepository $repo)
    {
        $articles = $repo->findByOrder();
        
        return $this->render('news/index.html.twig', [
            'articles' => $articles
        ]);
    }

    /**
     * @Route("/", name="home")
     */
    public function home() {
        return $this->render('news/home.html.twig');
    }

    /**
     * @Route("admin/news/new", name="news_create")
     * @Route("admin/news/{id}/{title}/edit", name="news_edit")
     */
    public function form(News $article = null, Request $request, ObjectManager $manager) {
        if (!$article) {
            $article = new News();
        }

        $form = $this->createForm(NewsType::class, $article);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            if(!$article->getId()) {
                $article->setCreatedAt(new \DateTime());
            }

            $manager->persist($article);
            $manager->flush();

            return $this->redirectToRoute('news_show', [
                'id' => $article->getId(),
                'title' => $article->getSlug()
            ]);
        }

        return $this->render('admin/create.html.twig', [
            'formNews' => $form->createView(),
            'editMode' => $article->getId() !== null
        ]);
    }

    /**
     * @Route("admin/news/{id}/{title}/delete", name="news_delete")
     */
    public function delete(News $article, objectManager $manager) {
        $manager->remove($article);
        $manager->flush();

        return $this->redirectToRoute('news');
    }

    /**
     * @Route("/news/{id}/{title}", name="news_show")
     */
    public function show(News $article, Request $request, ObjectManager $manager) {
        $comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setCreatedAt(new \DateTime)
                    ->setNews($article);

            $manager->persist($comment);
            $manager->flush();

            return $this->redirectToRoute('news_show', [
                'id' => $article->getId(),
                'title' => $article->getSlug('title')
            ]);
        }

        return $this->render('news/show.html.twig', [
            'article' => $article,
            'commentForm' => $form->createView()
        ]);
    }
}

templates/news/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h1 class="display-5">Bienvenue sur ce site de gestion de livres !</h1>
{% if app.user %}
<a href="{{ path('profil_membre', {'id' : app.user.id, 'username' : app.user.username}) }}" class="btn btn-primary btn-sm mb-3">Mon profil</a>
<p>Bonjour {{ app.user.username }}, votre rôle est {{ app.user.roles[0] }}.</p>

{% endif %}
<div class="row pl-3">
    <div class="card text-white bg-primary mb-3 mr-3" style="max-width: 20rem;">
        <div class="card-header">Atout du site</div>
        <div class="card-body">
            <p class="card-text">Consultation de news, commentaires, inscription, votre collection de livres, profils publics.</p>
        </div>
    </div>
      
    <div class="card text-white bg-warning mb-3 mr-3" style="max-width: 20rem;">
        <div class="card-header">Les modérateurs</div>
        <div class="card-body">
            <p class="card-text">Les modérateurs peuvent éditer les news, les commentaires, les fiches des livres.</p>
        </div>
    </div>
    
    <div class="card text-white bg-danger mb-3" style="max-width: 20rem;">
        <div class="card-header">Les super modérateurs</div>
        <div class="card-body">
            <p class="card-text">Les super modérateurs peuvent supprimer une news, les commentaires, les fiches des livres.</p>
        </div>
    </div>
</div>

{% endblock %}

templates/news/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Liste des news
{% endblock %} 

{% block body %}
    <section class="row mx-auto">
        {% for article in articles %}
        <article class="card text-white bg-primary mb-3 mr-3" style="max-width: 20rem;">
            <div class="card-header">{{ article.title }}</div>
            <div class="card-body">
                <div class="card-title">Écrit le {{ article.createdAt | date('d/m/Y' )}} à {{ article.createdAt | date('H:i') }}</div>
            </div>
            <div class="card-text ml-3">
                <img class="mb-3" src="{{ article.image }}" alt="image_news" width="70%">
                <div class="mb-3">{{ article.content | raw }}</div>
                <a href="{{ path('news_show', {'id' : article.id, 'title' : article.slug}) }}" class="btn btn-secondary mb-3">Lire la suite</a>
            </div>
        </article>
        {% endfor %}
    </section>
{% endblock %}

templates/news/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{{ article.title }}
{% endblock %}

{% block body %}

<article class="mb-5">
    <h1 class="display-5">{{ article.title }}</h1>
    <div class="metadata">Écrit le {{ article.createdAt | date('d/m/Y' )}} à {{ article.createdAt | date('H:i') }}</div>
    <div class="content">
        <img src="{{ article.image }}" alt="">
        <div><p>{{ article.content | raw }}</p></div>
    </div>
    {% if is_granted('ROLE_ADMIN') %}
    <a href="{{ path('news_edit', {'id' : article.id, 'title' : article.slug}) }} " class="btn btn-outline-warning">Éditer la news</a>
    {% endif %}

    {% if is_granted('ROLE_SUPER_ADMIN') %}
    <a href="{{ path('news_delete', {'id' : article.id, 'title' : article.slug}) }} " class="btn btn-outline-danger">Supprimer la news</a>
    {% endif %}
</article>
<section id="commentaires">
        <h1 class="display-5">{{ article.comments | length }} Commentaires :</h1>
    {% for comment in article.comments %}
    <div class="card border-primary mb-3" style="max-width: 30rem;">
        
            <div class="card-header">{{comment.author}}</div>
            <div class="card-text pl-3 pt-3">
                <p>{{comment.content | raw | nl2br }}</p>
            </div>
            <div class="card-text pl-3">
                <p>Écrit le {{comment.createdAt | date('d/m/Y à H:i')}}</p>
            </div>
            
    </div>
    <div class="mb-3">
        {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('comment_edit', {'id' : comment.id}) }}" class="btn btn-outline-warning">Éditer le commentaire</a>
        {% endif %}

        {% if is_granted('ROLE_SUPER_ADMIN') %}
        <a href="{{ path('comment_delete', {'id' : comment.id}) }}" class="btn btn-outline-danger">Supprimer le commentaire</a>
        {% endif %}
    </div>
        
    {% endfor %}

    <hr class="my-4">
    
    {% if app.user %}

    <h2 class="display-5">Ajouter un commentaire :</h2>

    <p><span class="redFields">*</span> Champ obligatoire</p>

    {{ form_start(commentForm) }}
    
    {{ form_row(commentForm.author, {'attr': {'placeholder': "Nom" }}) }}
    
    {{ form_row(commentForm.content, {'attr': {'placeholder': "Contenu" }}) }}
    
    <button type="submit" class="btn btn-success">Commenter</button>
    
    {{ form_end(commentForm) }}

    {% else %}
    
    <h2>Vous ne pouvez pas commenter !</h2>
    <a href="{{ path('security_login') }}" class="btn btn-primary">Connexion</a>
    
    {% endif %}
</section>

{% endblock %}